### ISSUE TITLE
How can I  access ip camera feed remotely 

### ISSUE THREAD

**Issue by skromandev** [rvi/ONVIFCamera#10] opened 2020-01-21 07:04 UTC
Hello, 

I was able to stream my camera locally successfully .
Now , how can I stream it remotely when I am not connected to local network ?
I tried few tutorials but no luck . 
Note: I would like to stream through owned server or bought server but can you suggest camera which is compatible with the library!!

Many thanks.

**Comment by rvi** [comment] 2020-01-22 15:22
If you're able to stream locally then the problem is from the configuration of your network, not the library or the camera, the camera should be accessible from outside, you should redirect the traffic on a given port to the internal IP of the camera. Closing this ticket as it's not related to the library.

**Closed by rvi** 2020-01-22 15:22 UTC
