### ISSUE TITLE
Issue after importing ONVIFCAMERA

### ISSUE THREAD

**Issue by skromandev** [rvi/ONVIFCamera#9] opened 2020-01-07 08:59 UTC
I get an error "soapengine.h" file not found and Could not build Objective-C module 'ONVIFCamera'.

Please suggest solution for this using Xcode 11.2

**Comment by rvi** [comment] 2020-01-07 12:53
Did you run `pod install`?

**Comment by skromandev** [comment] 2020-01-08 05:05
Yes , I did.
No issues or warning from pod end . Issue is with respect to some parser.

**Comment by skromandev** [comment] 2020-01-08 07:18
So basically the errors faced when run on simulator or actual device is
like below :


*2020-01-08 10:43:23.181137+0530 IPCAMERA[941:27397] creating player
instance using shared library*

*2020-01-08 10:43:23.240753+0530 IPCAMERA[941:27397] [plugin]
AddInstanceForFactory: No factory registered for id <CFUUID 0x600001e1bf40>
F8BB1C28-BAE8-11D6-9C31-00039315CD46*

*nil*

*2020-01-08 10:43:32.294816+0530 IPCAMERA[941:31554] Initializing
SOAPEngine v.1.41*

*2020-01-08 10:43:33.584808+0530 IPCAMERA[941:31829] []
nw_proxy_resolver_create_parsed_array [C1 proxy pac] Evaluation error:
NSURLErrorDomain: -1004*

*2020-01-08 10:43:33.646171+0530 IPCAMERA[941:31828] CredStore -
performQuery - Error copying matching creds.  Error=-25300, query={*

*    atyp = http;*

*    class = inet;*

*    "m_Limit" = "m_LimitAll";*

*    ptcl = http;*

*    "r_Attributes" = 1;*

*    sdmn = "index.html";*

*    srvr = "192.168.0.2";*

*    sync = syna;*

*}*

*2020-01-08 10:43:33.661012+0530 IPCAMERA[941:31831] []
nw_proxy_resolver_create_parsed_array [C2 proxy pac] Evaluation error:
NSURLErrorDomain: -1004*

*2020-01-08 10:43:33.800516+0530 IPCAMERA[941:31831] []
nw_proxy_resolver_create_parsed_array [C3 proxy pac] Evaluation error:
NSURLErrorDomain: -1004*

*:1: parser error : Start tag expected, '<' not found*

*Error 404: Not Found*

*^*

*:1: parser error : Start tag expected, '<' not found*

*Error 404: Not Found*

*^*

*:1: parser error : Start tag expected, '<' not found*

*Error 404: Not Found*

*^*

*Can't connect to the camera for an unknow reason. Status code: 404*

*SOAP REQUEST: Optional("http://www.onvif.org/ver10/device/wsdl/GetServices
<http://www.onvif.org/ver10/device/wsdl/GetServices>")*

*response: Optional([:])*


*And I am not able to figure out this .*

*So can you please throw some light on this ?*


Also I am getting the same error on simulator end when tried that sample
key.....


And would this be solved on buying soap license because I tried with
simulator and same error came .
I have ip of my camera as "192.168.0.2" and nothing else , would this much
sufficient help me in streaming ? Or something else is needed on server end
?

Please educate me on this.

Thanks & Regards

**Comment by rvi** [comment] 2020-01-08 08:57
I never saw this before. Try to remove CredStore, try just with my demo app and nothing else, it should work.

**Comment by skromandev** [comment] 2020-01-08 11:35
Using latest pods for mobilevlckit 3.3.9, still facing the issue .

**Comment by rvi** [comment] 2020-01-08 19:31
Yes this has nothing to do with VLC. you’re camera might return an invalid response, you can debug and print it, you will be able to check it’s validity online. Have you remove CredStore?

**Comment by skromandev** [comment] 2020-01-09 04:31
Where is credstore and what is it not able to find it trough normal search?

**Comment by rvi** [comment] 2020-01-13 13:40
My bad, I thought it was an external library, but it's used by iOS, maybe [this thread](https://stackoverflow.com/questions/46099940/credstore-perform-query-error) can help you.

**Comment by skromandev** [comment] 2020-01-14 04:32
OK thanks.

**Comment by skromandev** [comment] 2020-01-17 10:16
Hi,

I finally got it working using the url  "rtsp://192.168.225.225:554/12" .
Now , I identified the port "554" using other ip camera based apps .
I am not sure what this "/12" means and why this is appended ?

**Comment by rvi** [comment] 2020-01-17 19:27
Sorry, I don't know, it wasn't the case with the cameras I used.

**Comment by rvi** [comment] 2020-01-22 15:23
Closing this one as the problem is fixed in #10

**Closed by rvi** 2020-01-22 15:23 UTC
